sudo: true
language: ruby
script:
  - bundle exec rspec
matrix:
  include:
  - rvm: system
    before_install:
      - rvm get head
      - rvm use truffleruby --install --fuzzy --debug
      - gem install bundler
    install:
      - bundler install # --deployment doesn't work currently
