sudo: false
language: ruby
install:
  - free -m
  - cat /sys/fs/cgroup/memory/memory.stat
  - cat /sys/fs/cgroup/memory/memory.usage_in_bytes
  - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
script:
  - ruby -e '200.times.map { |i| s="a" * (100*(2**20)); p (i+1)/10.0; s }'
rvm:
  - 2.6.0
