sudo: false
language: ruby
script:
  - rvm autolibs disable
  - curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
  - curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
  - rvm get master
  - ls ~/.rvm/hooks
  - rm ~/.rvm/hooks/after_use
  - rvm --trace install truffleruby
  - rvm use truffleruby
  - ruby -v
rvm:
  - 2.5.3
