sudo: false
language: ruby
install:
  - free -m
  - cat /sys/fs/cgroup/memory/memory.stat
  - cat /sys/fs/cgroup/memory/memory.usage_in_bytes
  - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
  - ruby --native.Xmn1g --native.XX:+PrintGC --cpusampler --cpusampler.SampleInternal=true --cpusampler.Mode=roots -S bundle install -j1 --deployment
script:
  - true
rvm:
  - truffleruby
