sudo: false
language: ruby
before_script:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS
script:
  - bundle exec rspec
matrix:
  include:
  - rvm: 2.2.9
  - rvm: 2.3.6
  - rvm: 2.4.3
  - rvm: 2.5.0
    before_install:
      # https://github.com/travis-ci/travis-ci/issues/8978
      - gem update --system
  - rvm: ruby-head
    before_install:
      # https://github.com/travis-ci/travis-ci/issues/8978
      - gem update --system
  - jdk: oraclejdk8
    install:
      - curl -L https://github.com/eregon/truffleruby-native-releases/releases/download/2018-01-18/truffleruby-native-linux-amd64.tar.gz | tar xz
      - export PATH="$PWD/truffleruby/bin:$PATH"
      - export TRUFFLERUBY_RESILIENT_GEM_HOME=true
      - bundle install
    addons:
      apt:
        packages:
        - libc++-dev
        - libc++abi1
