os: osx
osx_image: xcode9.4
language: ruby
rvm: system
install:
- curl -L https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc3/truffleruby-1.0.0-rc3-macos-amd64.tar.gz | tar xz
- export PATH="$PWD/truffleruby-1.0.0-rc3-macos-amd64/bin:$PATH"
- export AOT_BIN="$PWD/truffleruby-1.0.0-rc3-macos-amd64/bin/ruby"
script:
- ruby -ropenssl -e 'p [OpenSSL::OPENSSL_LIBRARY_VERSION, OpenSSL::OPENSSL_VERSION]'
- ruby -ropen-uri -e "puts open(%{https://rubygems.org/}) { |f| f.read }[0,1000]"
- git clone --branch rc3-testing --depth 1 https://github.com/eregon/truffleruby.git
- cd truffleruby
- ruby spec/mspec/bin/mspec run --config spec/truffle.mspec --excl-tag fails --excl-tag graalvm --excl-tag aot -t $AOT_BIN :library_cext
- echo 'def trap(sig, prc=nil, &block); if sig != "INFO" && sig != :INFO; super; end; end' >> src/main/ruby/core/kernel.rb
- tool/jt.rb test mri --native --openssl
