sudo: false
language: ruby
install:
  - ruby --native.Xmn1g --native.XX:+PrintGC --cpusampler --cpusampler.SampleInternal=true --cpusampler.Mode=roots -S bundle install -j1 --deployment
script:
  - bundle exec rspec
rvm:
  - truffleruby
