sudo: false
language: ruby
install:
  - free -m
  - ruby --native.Xmn1g --native.XX:+PrintGC --cpusampler --cpusampler.SampleInternal=true --cpusampler.Mode=roots -S bundle install -j1 --deployment
script:
  - true
rvm:
  - truffleruby
