sudo: false
language: ruby
script:
  - bundle exec rspec
matrix:
  include:
  - rvm: 2.4.4
  - name: TruffleRuby
    rvm: system
    install: true
    script:
      - rvm get master
      - rvm autolibs disable
      # - rvm use truffleruby --debug --install --binary --fuzzy
      - rvm install truffleruby --debug --fuzzy
after_failure:
  - cat /home/travis/.rvm/log/*_truffleruby/update_system.log
