sudo: false
language: ruby
script:
  - bundle exec rspec
matrix:
  include:
  - name: TruffleRuby
    rvm: system
    install:
      - export TRUFFLERUBY_VERSION=1.0.0-rc6
      - curl -L https://github.com/oracle/truffleruby/releases/download/vm-$TRUFFLERUBY_VERSION/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64.tar.gz | tar xz
      - export PATH="$PWD/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64/bin:$PATH"
      - ruby --native.XX:+PrintGC --cpusampler --cpusampler.SampleInternal=true -S gem install bundler
      - ruby --native.XX:+PrintGC --cpusampler --cpusampler.SampleInternal=true -S bundle install -j1
