sudo: false
language: ruby
script:
  - bundle exec rspec
matrix:
  include:
  - rvm: 2.4.4
  - name: TruffleRuby
    rvm: system
    install:
      - rvm get master
      - rvm use truffleruby --install --binary --fuzzy
after_failure:
  - cat /home/travis/.rvm/log/*_truffleruby/update_system.log
