sudo: true
language: ruby
script:
  - bundle exec rspec
matrix:
  include:
  - rvm: system
    before_install:
      - rvm get head
      - rvm --debug mount -r https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc2/truffleruby-1.0.0-rc2-linux-amd64.tar.gz
      - rvm list
      - rvm use truffleruby
      - gem install bundler
    install:
      - bundler install # --deployment doesn't work currently
