sudo: false
language: ruby
script:
  - curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
  - curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
  - rvm get master
  - rvm --trace install truffleruby
  - rvm use truffleruby
  - ruby -v
rvm:
  - 2.5.3
