name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 'truffleruby' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eregon/use-ruby-action@master
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install -j1
      env:
        TRUFFLERUBYOPT: "--experimental-options --cpusampler --cpusampler.Mode=roots --cpusampler.SampleInternal --cpusampler.Output=json --cpusampler.OutputFile=profile.json"
    - uses: actions/upload-artifact@v1
      with:
        name: profile
        path: profile.json
    #- run: bundle exec rspec
